<a href="https://colab.research.google.com/github/tanzilalok/heart-disease-prediction/blob/main/Heart_Diseases_prediction379_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First I should import the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data collection and processing

In [ ]:
heart_data = pd.read_csv('/content/heart.csv')

In [ ]:
# printing the 5 dataset to check if everything running smoothly
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [ ]:
heart_data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [ ]:
# how to check the number of rows and collumns are in the data set ?
heart_data.shape

(303, 14)

In [ ]:
# how to get some information from the dataset ?
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [ ]:
# How can i check the mission values? if there is missing values we have handle missing values by the method computation
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
# statistical measures of the data
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
# checking the distributions of target value.
heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

-> 1 = Defective heart
-> 0 = healthy heart

In [ ]:
# spliting the features and target, when we are droping a collumn we have to write axis=1 and for dropping row we need to write axis=0
x = heart_data.drop(columns='target' , axis=1)
y = heart_data['target']

In [ ]:
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [ ]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

spitting the data into training data and testing data

In [1]:
heart_data.head()

NameError: name 'heart_data' is not defined

In [2]:
heart_data.head()

NameError: name 'heart_data' is not defined

In [3]:
heart_data = pd.read_csv('/content/heart.csv')

NameError: name 'pd' is not defined

In [4]:
heart_data = pd.read_csv('/content/heart.csv')

NameError: name 'pd' is not defined

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [6]:
heart_data = pd.read_csv('/content/heart.csv')

In [7]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [8]:
heart_d = pd.read_csv('/content/sample_data/heart.csv')

In [9]:
heart_data.shape

(303, 14)

In [10]:
x = heart_d.drop(columns='target' , axis=1)
y = heart_d['target']

In [11]:
#spitting the data into training data and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state= 2 )

NameError: name 'X' is not defined

In [12]:
heart_d.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,
    stratify=Y,
    random_state=2
)

NameError: name 'X' is not defined

In [14]:
x = heart_d.drop(columns='target' , axis=1)
y = heart_d['target']

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=Y,
    random_state=2
)

NameError: name 'Y' is not defined

In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=y,
    random_state=2
)

NameError: name 'Y' is not defined

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(
    x, y,
    test_size=0.2,
    stratify=y,
    random_state=2
)

In [19]:
print(x.shape , X_train.shape , X_test.shape)

(303, 13) (242, 13) (61, 13)

Model training

In [20]:
model = LogisticRegression()

In [21]:
#training the logistic regression model with training data
model.fit(X_train , Y_train) #model just finding the pattern from the given data

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [22]:
model = LogisticRegression(max_iter=1000)

In [23]:
model.fit(X_train , Y_train)

LogisticRegression(max_iter=1000)

In [24]:
#model evaluation
#accuracy score
#now accuracy on training data
X_train_prediction = model.predict(X_train)
training_Data_Accuracy = accuracy_score(X_train_prediction , Y_train)

In [25]:
print('Accuracy on training data :' , training_Data_Accuracy)

Accuracy on training data : 0.8553719008264463

In [26]:
#now accuracy on test data
X_test_prediction = model.predict(X_test)
testing_Data_Accuracy = accuracy_score(X_test_prediction , Y_test)

In [27]:
print('Accuracy on testing data :' , testing_Data_Accuracy)

Accuracy on testing data : 0.8032786885245902

Building a predictive system

In [28]:
input_data = (41,0,1,130,204,0,0,172,0,1.4,2,0,2)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction) #lest see the actual prediction is 1 so lets see if it can predict

[1]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [30]:
input_data = (63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction) #lest see the actual prediction is 1 so lets see if it can predict

[1]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [31]:
new_patient = pd.DataFrame([[
    63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1
]], columns=x.columns)

prediction = model.predict(new_patient)

print("Prediction:", prediction)

NameError: name 'X' is not defined

In [32]:
new_patient = pd.DataFrame([[
   76,0,2,140,197,0,2,116,0,1.1,1,0,2
]], columns=x.columns)

prediction = model.predict(new_patient)

print("Prediction:", prediction)

if (prediction[0] == 0):
  print('The person does not have any heart diseases')
else :
  print('The person have heart diseases')

Prediction: [1]

In [33]:
new_patient = pd.DataFrame([[
   76,0,2,140,197,0,2,116,0,1.1,1,0,2
]], columns=x.columns)

prediction = model.predict(new_patient)

print("Prediction:", prediction)

if (prediction[0] == 0):
  print('The person does not have any heart diseases')
else :
  print('The person have heart diseases')

Prediction: [1]
The person have heart diseases

In [34]:
new_patient = pd.DataFrame([[
   58,1,0,114,318,0,2,140,0,4.4,0,3,1
]], columns=x.columns)

prediction = model.predict(new_patient)

print("Prediction:", prediction)

if (prediction[0] == 0):
  print('The person does not have any heart diseases')
else :
  print('The person have heart diseases')

Prediction: [0]
The person does not have any heart diseases